stages:
  - name: update
    if: branch = master AND type = cron
  - name: test
    if: branch = master AND type = cron

matrix:
  include:
    - stage: update
      language: python
      script: |
        if [ -n "$GH_TOKEN" -a -n "$TX_TOKEN" ]; then
          tx pull --parallel -asf
          git add .
          git -c user.name='vue-cli-locales-bot' -c user.email='vue-cli-locales-bot@caugner.de' commit -m "[tx-bot] updated from transifex"
          git push -f -q https://vue-cli-locales-bot:$GH_TOKEN@github.com/caugner/vue-cli-locales "$TRAVIS_BRANCH" &> /dev/null
        fi
    - stage: test
      language: node_js
